image: dalibo/jekyll_docker

pipelines:
  branches:
    master:
      - step:
          script:
            - '[ -f Gemfile ] && bundle install'
            - gem install bundler
            - bundle exec jekyll build
            - ssh-keyscan -p 222 -t rsa 88.99.169.45 >> ~/.ssh/known_hosts
            - rsync -clvrz -e "ssh -p 222" _site/ $DEV_DEPLOY_URL
    feature/*:
      - step:
          script:
            - '[ -f Gemfile ] && bundle install'
            - gem install bundler
            - bundle exec jekyll build --config "_config.yml,_config_dev.yml"
            - ssh-keyscan -p 222 -t rsa 88.99.169.45 >> ~/.ssh/known_hosts
            - rsync -rvz -e "ssh -p 222" _site/ $DEV_DEPLOY_URL
